import type { Metadata } from "next";
import { Outfit, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import { AuthProvider } from "@/context/AuthContext";


const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-outfit", 
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Deu Negócio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" >
      
      <body
        className={`${spaceGrotesk.variable} ${outfit.variable} mt-24 antialiased h-screen bg-background text-foreground font-outfit`}
      >
        <Toaster position="bottom-right" />
        
          <AuthProvider>
            <Header/>
            {children}
          </AuthProvider>

      </body>
    </html>
  );
}
